### ISSUE TITLE
action 블럭에서 토픽 검색중 중단할 경우 발생하는 에러 

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/concert_workflow_engine#10]
action 블럭에서 토픽을 검색하는 도중에 workflow disable 명령을 내리거나 모니터링에서에서 kill 할 경우 
다음과 같은 에러를 발생합니다. 확인 부탁드립니다. 

```
info: will kill engine : 16880
info: engine-16880 /home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/engine.js:328
    return process_send2({cmd: 'release_resource', requester_id: req_id});
                                                                 ^
info: engine-16880 ReferenceError: req_id is not defined
    at /home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/engine.js:328:66
    at arrayMap (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/lodash/index.js:1430:25)
    at Function.map (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/lodash/index.js:6516:14)
    at Engine.clear (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/engine.js:327:17)
    at process.<anonymous> (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/engine_runner.js:54:15)
    at process.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at Pipe.channel.onread (child_process.js:349:11)
[INFO] [WallTime: 1428481337.397132] Client disconnected. 3 clients total.
```

**Comment by eskim** [comment]
계속 문제가 발생하나요?

**Comment by dwlee** [comment]
중단되는것을 확인하였습니다. 
닫아도 될것 같습니다.
