### ISSUE TITLE
workflow engine이 죽을 때 자원 해제 관련

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/concert_workflow_engine#14]
현재는 child process 엔진이 죽을때, 사용중인 자원을 모두 해제하고 죽습니다. 
하지만 workflow engine이 종료 될때에는 child process 에서 사용중인 자원은 해제하지 못하는 문제가 있습니다. 확인 부탁드립니다.

**Comment by dwlee** [comment]
다음과 같은 에러가 발생합니다. 

```
[INFO] [WallTime: 1434625737.527418] Blockly Workflow Handler : disable workflow [service name: live_authoring]
info: will kill engine : 23633

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: channel closed
    at ChildProcess.target.send (child_process.js:406:26)
    at EngineManager.killEngine (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/src/engine_manager.js:385:8)
    at EngineManager.enableWorkflows (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/src/engine_manager.js:109:10)
    at wrapper (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/lodash/index.js:3128:19)
    at Topic.<anonymous> (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/src/ros.js:103:30)
    at Topic.EventEmitter.emit (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/roslib/node_modules/eventemitter2/lib/eventemitter2.js:317:21)
    at RosTCP.Topic._messageCallback (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/roslib/src/core/Topic.js:53:10)
    at RosTCP.EventEmitter.emit (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/roslib/node_modules/eventemitter2/lib/eventemitter2.js:317:21)
    at handleMessage (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/roslib/src/core/SocketAdapter.js:66:14)
    at WebSocket.onMessage (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/roslib/src/core/SocketAdapter.js:113:9)
    at WebSocket.onMessage (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/roslib/node_modules/ws/lib/WebSocket.js:355:18)
    at WebSocket.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/roslib/node_modules/ws/lib/WebSocket.js:682:10)
    at Receiver.opcodes.1.finish (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/roslib/node_modules/ws/lib/Receiver.js:391:14)
    at Receiver.expectHandler (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/roslib/node_modules/ws/lib/Receiver.js:378:31)
    at Receiver.add (/home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/roslib/node_modules/ws/lib/Receiver.js:87:24)
[INFO] [WallTime: 1434625737.552559] Client disconnected. 2 clients total.
[software/workflow_engine_blockly/workflow_engine_blockly-4] process has died [pid 17599, exit code 8, cmd /home/yujin/ros/yujinrnd/src/concert_workflow_engine/concert_workflow_engine_blockly/concert_workflow_engine_blockly.js --port 9999 --rosbridge_port 9091 --rosbridge_address localhost --action_delay 2000 --publish_delay 200 --log_level info __name:=workflow_engine_blockly __log:=/home/yujin/.ros/log/4d4ce6d2-15a6-11e5-ac01-fcaa142ef813/software-workflow_engine_blockly-workflow_engine_blockly-4.log].
log file: /home/yujin/.ros/log/4d4ce6d2-15a6-11e5-ac01-fcaa142ef813/software-workflow_engine_blockly-workflow_engine_blockly-4*.log
Workflows Handler Blockly : Bye Bye
```

**Comment by dwlee** [comment]
526e1f8d9de2e3e61ad789640de1599cc09a35ad
패치 하였습니다.
