### ISSUE TITLE
자원 할당시 timeout 발생할 경우 에러 발생

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/concert_workflow_engine#21]
https://github.com/robotics-in-concert/rocon_composer/issues/37 을 테스트 해보고 있습니다. 

자원 할당시 설정된 timeout을 테스트 하고 있습니다. 
engine에서 리소스 할당에 대한  `waiting` 이고, 이때 timeout 이 발생한 경우 
다음과 같은 에러가 발생하였습니다. 
`resource allocation timeout`은 workflow에서 로그를 출력한것입니다. 

```
info: socket.io client connected id:AOTgM_77mNTdGkE5AAAB

info: resource allocation timeout. { rapp: 'rocon_apps/talker',
  id: { bytes: [ 70, 106, 34, 67, 225, 119, 77, 200, 188, 183, 130, 228, 33, 199, 31, 158 ] },
  uri: 'rocon:/talker',
  remappings: [ { remap_from: 'chatter', remap_to: '/chatter' } ],
  parameters: 
   [ { key: 'message', value: 'hello world' },
     { key: 'frequency', value: '10' } ] } 10000
RESULT [ null ]

info: engine-12933 Unhandled rejection TypeError: Cannot read property 'req_id' of null
    at /home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/engine.js:209:48
    at tryCatcher (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)
```

**Comment by eskim** [comment]
수정하였습니다. 다시 한번 확인 부탁드립니다.

**Comment by dwlee** [comment]
해당 에러가 발생하지 않습니다. 
이슈는 닫겠습니다.
