### ISSUE TITLE
지속적인 리소스 재 할당시 memory leak 에러 

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/concert_workflow_engine#25]
리소스를 지속적으로 재 할당하면 다음과 같은 에러가 발생합니다.

```
info: engine-815 Mon May 11 2015 09:52:49 GMT+0900 (KST) - Rocon Authoring :"[Pickup Delivery]  Resource Allocation Failure"
info: engine-815 Mon May 11 2015 09:52:49 GMT+0900 (KST) - Rocon Authoring :"[Pickup Delivery]  Push ReNew Order: [Cnt: 1] []"
info: engine-815 Mon May 11 2015 09:52:49 GMT+0900 (KST) - Rocon Authoring :"[Pickup Delivery]  Pop Order: [Cnt: 0] [[object Object]]"
Mon May 11 2015 09:52:49 GMT+0900 (KST) - Rocon Authoring :"[Pickup Delivery] Assign new robot: [] [order id: b72c6cfe-1b80-4ad2-897c-64ffdb95a808] [locations: table4] [menus: ]"
info: engine-815 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
info: engine-815 Trace
    at process.addListener (events.js:160:15)
    at process.on.process.addListener (node.js:802:26)
    at /home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/utils.js:25:13
    at tryCatcher (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/promise.js:53:37)
    at process_send2 (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/utils.js:24:10)
    at Engine.allocateResource (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/engine.js:205:3)
    at eval (eval at <anonymous> (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/engine.js:132:18), <anonymous>:150:36)
[INFO] [WallTime: 1431305569.525738] [Client 0] Subscribed to /concert/scheduler/requests_9fc00774e4304662acfa6153ef23d795
[INFO] [WallTime: 1431305569.569245] requester feedback topic: ~requests_9fc00774e4304662acfa6153ef23d795
[INFO] [WallTime: 1431305577.295728] Scheduler : releasing resources from cancelled request [['concert_common_rapps/pickup_delivery']][scheduler-requester watchdog timeout]


```

**Comment by eskim** [comment]
에러를 보니 leak 의 가능성이 있다는 얘기로 보이네요. 우선 max listener 를 넉넉하게 설정해 두었습니다.

가능하다면 listener 를 해제할 수 있는 지점이 있는지 확인해 보겠습니다.

**Comment by dwlee** [comment]
set max listener을 큰 수로 늘려도 에러가 발생합니다. 

```
info: engine-17263 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
info: engine-17263 Trace
    at process.addListener (events.js:160:15)
    at process.on.process.addListener (node.js:802:26)
    at /home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/utils.js:25:13
    at tryCatcher (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/bluebird/js/main/promise.js:53:37)
    at process_send2 (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/utils.js:24:10)
    at Engine.socketBroadcast (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/engine.js:55:3)
    at $engine.runScheduledAction.$engine.pub.orders (eval at <anonymous> (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/engine.js:132:18), <anonymous>:129:61)
    at /home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/engine.js:324:22
    at Goal._onFeedback (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/src/ros.js:206:49)
    at Goal.EventEmitter.emit (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/eventemitter2/lib/eventemitter2.js:339:22)
    at Topic.<anonymous> (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/roslib/src/actionlib/ActionClient.js:88:12)
    at Topic.EventEmitter.emit (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/eventemitter2/lib/eventemitter2.js:317:21)
    at RosTCP.Topic._messageCallback (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/roslib/src/core/Topic.js:53:10)
    at RosTCP.EventEmitter.emit (/home/dwlee/work/rocon_ws/src/concert_workflow_engine/concert_workflow_engine_blockly/node_modules/eventemitter2/lib/eventemitter2.js:317:21)

```

**Comment by dwlee** [comment]
ros에서 사용하는 eventemitter2 부분에서도 maxListener 를 설정하는 옵션이 있습니다. 
그래서 다음과 같이 [EventEmitter2 선언시](https://github.com/robotics-in-concert/concert_workflow_engine/blob/master/concert_workflow_engine_blockly/src/ros.js#L12) 추가 옵션을 설정하였습니다.

```
EventEmitter2.call(this, {wildcard: true, maxListeners:1024});
```

하지만 근본적인 해결책은 아닙니다. listener를 해제할 부분에 대해 살펴봐야 합니다.

**Comment by dwlee** [comment]
a690f26e49e8304cc6dd95ec65f146bbc688fd0a
의견을 반영하여 업데이트 하였습니다.
